// Generated by CoffeeScript 1.10.0
var app, bodyParser, express, path;

express = require('express');

bodyParser = require('body-parser');

path = require('path');

app = new express();

app.use(bodyParser.json());

app.use(express["static"](path.join(__dirname, 'public')));

app.listen(5900);

console.log('apiTools成功启动 http://127.0.0.1:5900');
