// Generated by CoffeeScript 1.10.0
var _, db, router;

router = require('express').Router();

db = require('../database').apiInfo;

_ = require('lodash');

router.get('/', function(req, res) {
  return db.find({}, function(err, info) {
    return res.json(info[0]);
  });
});

router.put('/', function(req, res) {
  var body;
  body = req.body;
  return db.findOne({}, function(err, info) {
    var keys;
    keys = Object.keys(info);
    _.forEach(info, function(n, key) {
      return info[key] = body[key];
    });
    info.save();
    return res.json(info);
  });
});

module.exports = router;
