// Generated by CoffeeScript 1.10.0
var LinvoDB, apiInfo, definitions, paths;

LinvoDB = require("linvodb3");

LinvoDB.defaults.store = {
  db: require("medeadown")
};

LinvoDB.dbPath = process.cwd() + '/database/';

apiInfo = new LinvoDB("apiInfo", {});

paths = new LinvoDB("paths", {});

definitions = new LinvoDB("definitions", {});

module.exports = {
  apiInfo: apiInfo,
  paths: paths,
  definitions: definitions
};
